name: "Build and test"

on:
  pull_request:

jobs:
  build:
    name: Build and Test logwhale
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        run: make test